// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLQEwfAaN35rP05BSOnumVP3VMpalVzOA',
    appId: '1:561345926495:web:27495083d57d60c77b92ea',
    messagingSenderId: '561345926495',
    projectId: 'signin-456a0',
    authDomain: 'signin-456a0.firebaseapp.com',
    storageBucket: 'signin-456a0.appspot.com',
    measurementId: 'G-4DSDRY9MSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGT4tkP4-zVqIjtpYxwdk0sSR-cl89vpg',
    appId: '1:561345926495:android:1c8a38bc2805271f7b92ea',
    messagingSenderId: '561345926495',
    projectId: 'signin-456a0',
    storageBucket: 'signin-456a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqNj6y3UKFQ2_2970GxbvG8-LM6bfpEy0',
    appId: '1:561345926495:ios:1343232934d64c917b92ea',
    messagingSenderId: '561345926495',
    projectId: 'signin-456a0',
    storageBucket: 'signin-456a0.appspot.com',
    androidClientId: '561345926495-itpevtr3lk4d8fdb0bcu4evsj2af1k36.apps.googleusercontent.com',
    iosClientId: '561345926495-ae8n5g1nu1em9t6gro0rjjfkd1bslucm.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqNj6y3UKFQ2_2970GxbvG8-LM6bfpEy0',
    appId: '1:561345926495:ios:1343232934d64c917b92ea',
    messagingSenderId: '561345926495',
    projectId: 'signin-456a0',
    storageBucket: 'signin-456a0.appspot.com',
    androidClientId: '561345926495-itpevtr3lk4d8fdb0bcu4evsj2af1k36.apps.googleusercontent.com',
    iosClientId: '561345926495-ae8n5g1nu1em9t6gro0rjjfkd1bslucm.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLQEwfAaN35rP05BSOnumVP3VMpalVzOA',
    appId: '1:561345926495:web:01fbc89783d1b28c7b92ea',
    messagingSenderId: '561345926495',
    projectId: 'signin-456a0',
    authDomain: 'signin-456a0.firebaseapp.com',
    storageBucket: 'signin-456a0.appspot.com',
    measurementId: 'G-HTVRRXFN30',
  );
}
